package RangeIteratorDemo.sandbox.sandbox;

/*Generated by MPS */


public class Demo {
  public static void main(String[] args) {
    int number = 10;
    for (int index = 0; index < number + 10; index++) {
      System.out.println("Hi! " + index);
    }
  }
}
