package RangeIteratorDemo.sandbox.sandbox;

/*Generated by MPS */


public class Demo {
  public static void main(String[] args) {
    int start = 0;
    int end = 10;

    for (int index = start; index < end + 1; index++) {
      System.out.println("Hi! " + index);
    }
  }
}
