package RangeIteratorDemo.sandbox.sandbox;

/*Generated by MPS */


public class Demo {
  public static void main(String[] args) {
    int number = 10;

    for (int index_c0a = 0; index_c0a < number + 10; index_c0a++) {
      System.out.println("Hi!");
    }
  }
}
