package RangeIteratorDemo.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class RangeIterator_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public RangeIterator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RangeIteratorDemo.structure.RangeIterator";
  }
}
