package RangeIteratorDemo.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.scopes.runtime.ScopeUtils;
import jetbrains.mps.baseLanguage.scopes.Scopes;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class RangeIterator_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    if (SConceptOperations.isExactly(kind, "jetbrains.mps.baseLanguage.structure.VariableDeclaration")) {
      if (ScopeUtils.comeFrom("body", thisNode, child)) {
        return Scopes.forVariables(kind, SLinkOperations.getTarget(thisNode, "loopVariable", true), ScopeUtils.lazyParentScope(thisNode, kind));
      }
    }
    return ScopeUtils.lazyParentScope(thisNode, kind);
  }
}
