package RangeIteratorDemo.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.LocalVariableDeclaration_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IValidIdentifier_BehaviorDescriptor;

public class RangeIteratorVariable_BehaviorDescriptor extends LocalVariableDeclaration_BehaviorDescriptor implements IValidIdentifier_BehaviorDescriptor {
  public RangeIteratorVariable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RangeIteratorDemo.structure.RangeIteratorVariable";
  }
}
